<a href="https://colab.research.google.com/github/kawin7538/ActivityTimeCollector/blob/main/NLPTimeSchedulePrediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sqlalchemy import create_engine
import pandas as pd 
import numpy as np
import pickle

In [ ]:
csv_database = create_engine('postgres://upjumigwrlyrft:c97ced32104ca7965b303eb9d0e728aae7d755c9975e38d8ee9e86e5e4a53e25@ec2-54-157-234-29.compute-1.amazonaws.com:5432/dbgm4vp87c40j8')

In [ ]:
df=pd.read_sql_query('select * from activity',csv_database)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54 entries, 0 to 53
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   activity_id    54 non-null     int64  
 1   activity_name  54 non-null     object 
 2   activity_time  54 non-null     float64
dtypes: float64(1), int64(1), object(1)
memory usage: 1.4+ KB


In [ ]:
!pip install pythainlp
!pip install emoji

     |████████████████████████████████| 10.6MB 7.0MB/s 
     |████████████████████████████████| 747kB 46.3MB/s 
     |████████████████████████████████| 133kB 8.0MB/s 


In [ ]:
from pythainlp import word_vector,word_tokenize
from pythainlp.ulmfit import process_thai

Corpus: thai2fit_wv
- Downloading: thai2fit_wv 0.1


100%|██████████| 62452646/62452646 [00:01<00:00, 42323129.65it/s]


Corpus: wiki_lm_lstm
- Downloading: wiki_lm_lstm 0.32


100%|██████████| 1050919089/1050919089 [00:18<00:00, 55729992.45it/s]


Corpus: wiki_itos_lstm
- Downloading: wiki_itos_lstm 0.32


100%|██████████| 1530484/1530484 [00:00<00:00, 12633736.39it/s]


In [ ]:
df['processed']=df['activity_name'].map(lambda x: "|".join(process_thai(x)))
df["wc"] = df.processed.map(lambda x: len(x.split("|")))
df["uwc"] = df.processed.map(lambda x: len(set(x.split("|"))))
df

activity_id            activity_name  ...  wc uwc
0             2                  กินข้าว  ...   1   1
1             3               เกมยิงเรือ  ...   3   3
2             4                      พัก  ...   1   1
3             5                      พัก  ...   1   1
4             6                      พัก  ...   1   1
5            10         เกมมังกรมังกรทอง  ...   4   4
6            11            Open Ceremony  ...   2   2
7            12         Testing Ceremony  ...   2   2
8            13         Closing Ceremony  ...   2   2
9            14    ออกกำลังกายตอนเช้ามืด  ...   3   3
10           15           สวดมนต์ก่อนนอน  ...   3   3
11           16          กิจกรรมระดมสมอง  ...   2   2
12           17                สันทนาการ  ...   1   1
13           18        พักรับประทานอาหาร  ...   3   3
14           19              กินข้าวเช้า  ...   2   2
15           20       รับประทานอาหารเย็น  ...   2   2
16           21                 ทานอาหาร  ...   1   1
17           22        งานเลี้ยงสังสรรค์  ...   2   2
18           23              เกมไปรษณีย์  ...   2   2
19           24              เกมไปรษณีย์  ...   2   2
20           25     สวัสดีครับ ผมชื่อ...  ...   5   5
21           26     สวัสดีครับ ผมชื่อ...  ...   5   5
22           27          เกมหนังสือพิมพ์  ...   2   2
23           28             เกมของแทนตัว  ...   4   4
24           29             เกมของแทนตัว  ...   4   4
25           30               เกมลูกโป่ง  ...   2   2
26           31         เกมผ้าห่มซ่อนตัว  ...   3   3
27           32            เกมฉลากตัวเอง  ...   3   3
28           33            เกมฉลากตัวเอง  ...   3   3
29           34      เกมเก้าอี้เรียกชื่อ  ...   3   3
30           35          เกมตามล่าหาชื่อ  ...   4   4
31           36           เกมแลกป้ายชื่อ  ...   3   3
32           37           เกมแลกป้ายชื่อ  ...   3   3
33           38  ปรบมือ 2 ครั้ง แนะนำตัว  ...   4   4
34           39  ประมือ 2 ครั้ง แนะนำตัว  ...   4   4
35           40      แนะนำตัวพร้อมของฝาก  ...   3   3
36           41      แนะนำตัวพร้อมของฝาก  ...   3   3
37           42            เกม ของฉันหาย  ...   4   4
38           43            เกม ของฉันหาย  ...   4   4
39           44                  เกมรำวง  ...   2   2
40           45                  เกมรำวง  ...   2   2
41           46               เกม บอกรัก  ...   3   3
42           47                  โป๊ะแตก  ...   1   1
43           48                  โป๊ะแตก  ...   1   1
44           49       เกม จัดลำดับอวัยวะ  ...   3   3
45           50       เกม จัดลำดับอวัยวะ  ...   3   3
46           51                เกมบัดดี้  ...   3   3
47           52               เกมยิงเรือ  ...   3   3
48           53               เกมยิงเรือ  ...   3   3
49           54              แข่งทำอาหาร  ...   2   2
50           55                   อาบน้ำ  ...   1   1
51           56                   อาบน้ำ  ...   1   1
52           57         อาบน้ำและกินข้าว  ...   3   3
53           58         กินข้าวและอาบน้ำ  ...   3   3

[54 rows x 6 columns]

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LinearRegression

tfidf = TfidfVectorizer(tokenizer=process_thai, ngram_range=(1,3), sublinear_tf=True)
tfidf_fit=tfidf.fit(df['activity_name'])
text_train=tfidf_fit.transform(df['activity_name'])

/usr/local/lib/python3.7/dist-packages/sklearn/feature_extraction/text.py:507: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn("The parameter 'token_pattern' will not be used"


In [ ]:
text_train

<54x157 sparse matrix of type '<class 'numpy.float64'>'
	with 268 stored elements in Compressed Sparse Row format>

In [ ]:
tfidf.get_feature_names()

['...',
 '2',
 '2 ครั้ง',
 '2 ครั้ง แนะนำตัว',
 'ceremony',
 'closing',
 'closing ceremony',
 'open',
 'open ceremony',
 'testing',
 'testing ceremony',
 'xxwrep',
 'xxwrep มังกร',
 'xxwrep มังกร ทอง',
 'กรัก',
 'กิจกรรม',
 'กิจกรรม ระดมสมอง',
 'กินข้าว',
 'กินข้าว เช้า',
 'กินข้าว และ',
 'กินข้าว และ อาบน้ำ',
 'ก่อน',
 'ก่อน นอน',
 'ของ',
 'ของ ฉัน',
 'ของ ฉัน หาย',
 'ของ แทน',
 'ของ แทน ตัว',
 'ของฝาก',
 'ครับ',
 'ครับ ผม',
 'ครับ ผม ชื่อ',
 'ครั้ง',
 'ครั้ง แนะนำตัว',
 'งานเลี้ยง',
 'งานเลี้ยง สังสรรค์',
 'จัดลำดับ',
 'จัดลำดับ อวัยวะ',
 'ฉลาก',
 'ฉลาก ตัวเอง',
 'ฉัน',
 'ฉัน หาย',
 'ชื่อ',
 'ชื่อ ...',
 'ซ่อนตัว',
 'ดี้',
 'ตอน',
 'ตอน เช้ามืด',
 'ตัว',
 'ตัวเอง',
 'ตามล่า',
 'ตามล่า หา',
 'ตามล่า หา ชื่อ',
 'ทอง',
 'ทานอาหาร',
 'ทำอาหาร',
 'นอน',
 'บอ',
 'บอ กรัก',
 'บัด',
 'บัด ดี้',
 'ปรบมือ',
 'ปรบมือ 2',
 'ปรบมือ 2 ครั้ง',
 'ประมือ',
 'ประมือ 2',
 'ประมือ 2 ครั้ง',
 'ป้ายชื่อ',
 'ผม',
 'ผม ชื่อ',
 'ผม ชื่อ ...',
 'ผ้าห่ม',
 'ผ้าห่ม ซ่อนตัว',
 'พร้อม',
 'พร้อม ของฝาก',
 'พัก',
 

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler_fit = scaler.fit(df[["wc","uwc"]].astype(float))
num_train = scaler_fit.transform(df[['wc','uwc']])

In [ ]:
num_train

array([[-1.49797598, -1.49797598],
       [ 0.38320316,  0.38320316],
       [-1.49797598, -1.49797598],
       [-1.49797598, -1.49797598],
       [-1.49797598, -1.49797598],
       [ 1.32379273,  1.32379273],
       [-0.55738641, -0.55738641],
       [-0.55738641, -0.55738641],
       [-0.55738641, -0.55738641],
       [ 0.38320316,  0.38320316],
       [ 0.38320316,  0.38320316],
       [-0.55738641, -0.55738641],
       [-1.49797598, -1.49797598],
       [ 0.38320316,  0.38320316],
       [-0.55738641, -0.55738641],
       [-0.55738641, -0.55738641],
       [-1.49797598, -1.49797598],
       [-0.55738641, -0.55738641],
       [-0.55738641, -0.55738641],
       [-0.55738641, -0.55738641],
       [ 2.2643823 ,  2.2643823 ],
       [ 2.2643823 ,  2.2643823 ],
       [-0.55738641, -0.55738641],
       [ 1.32379273,  1.32379273],
       [ 1.32379273,  1.32379273],
       [-0.55738641, -0.55738641],
       [ 0.38320316,  0.38320316],
       [ 0.38320316,  0.38320316],
       [ 0.38320316,

In [ ]:
X_train = np.concatenate([num_train,text_train.toarray()],axis=1)
Y_train = df['activity_time']

In [ ]:
from sklearn.linear_model import LinearRegression

clf=LinearRegression()
clf.fit(X_train,Y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
clf.predict(X_train)

array([ 44.9362793 ,  31.62768555,  16.5144043 ,  16.5144043 ,
        16.5144043 ,  30.1159668 ,  14.94799805,   4.9362793 ,
        14.93237305,  60.05737305,  15.04956055,  60.01049805,
        19.8815918 ,  45.00268555,  89.9987793 ,  59.97143555,
        44.8972168 , 239.9831543 ,   7.45092773,   7.45092773,
        12.6472168 ,  12.6472168 ,  19.97924805,   7.5925293 ,
         7.5925293 ,  19.95581055,  20.0612793 ,  17.52612305,
        17.52612305,  20.0612793 ,  10.1159668 ,  17.54174805,
        17.54174805,  10.1862793 ,  20.1784668 ,  25.05737305,
        25.05737305,  12.6003418 ,  12.6003418 ,  17.4440918 ,
        17.4440918 ,  10.0612793 ,  24.92358398,  24.92358398,
        12.5378418 ,  12.5378418 ,  10.0456543 ,  31.62768555,
        31.62768555,  89.94018555,  37.2800293 ,  37.2800293 ,
        60.02612305,  75.01538086])

In [ ]:
clf.score(X_train,Y_train)

0.9903959340913117

In [ ]:
filename = 'finalized_model.sav'
pickle.dump(clf, open(filename, 'wb'))

# Testing Session

In [ ]:
test_df=pd.DataFrame(columns=df.columns)
to_append=[77,'กินข้าวตอนเที่ยง',0,0,0,0]
test_df.loc[len(test_df)]=to_append
test_df

activity_id     activity_name activity_time processed wc uwc
0          77  กินข้าวตอนเที่ยง             0         0  0   0

In [ ]:
test_df['processed']=test_df['activity_name'].map(lambda x: "|".join(process_thai(x)))
test_df["wc"] = test_df.processed.map(lambda x: len(x.split("|")))
test_df["uwc"] = test_df.processed.map(lambda x: len(set(x.split("|"))))
test_df

activity_id     activity_name activity_time          processed  wc  uwc
0          77  กินข้าวตอนเที่ยง             0  กินข้าว|ตอนเที่ยง   2    2

In [ ]:
text_test=tfidf_fit.transform(test_df['activity_name'])
num_test = scaler_fit.transform(test_df[['wc','uwc']])

In [ ]:
X_test = np.concatenate([num_test,text_test.toarray()],axis=1)
X_test

array([[-0.55738641, -0.55738641,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  1.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0. 

In [ ]:
clf.predict(X_test)

array([-4.73446775e+11])